import {createSlice, nanoid} from '@reduxjs/toolkit'

const initialState = {
    todos: [{
        id: 1,
        text: 'Learn Redux Toolkit',
    }]
} 
/*
State means: Current data of application.
Payload means: Actual data sent with action.
Slice means: A small part of your global app data + the logic to manage it.
*/
export const todoSlice = createSlice({
    name: 'todo',
    initialState,
    reducers: {
        addTodo: (state, action) => {
            const todo = {
                id: nanoid(),
                text: action.payload
            }
// Immer library is used to write "mutating" logic in reducers. 
// It allows us to write code that appears to mutate the state directly, 
// but it actually creates a new state object under the hood. 
// This is done by using a proxy object that tracks changes to the state and produces
// a new state object when the changes are complete.
            state.todos.push(todo)
        },
        removeTodo: (state, action) => {
            state.todos = state.todos.filter(todo => todo.id !== action.payload)
        },
        updateTodo: (state, action) => {
            const {id, text} = action.payload
            const todo = state.todos.find(todo => todo.id === id)
            if (todo) {
                todo.text = text
            }
            else{
                console.error(`Todo with id ${id} not found`)
            }
        },
        
    }
})

export const {addTodo, removeTodo, updateTodo} = todoSlice.actions
// todoSlice.reducer : Handles state updates inside store.
export default todoSlice.reducer

// Complete Steps for using creating Redux Toolkit: 

// 1. Create a slice using createSlice() function from @reduxjs/toolkit.
// 2. Define the initial state of the slice.
// 3. Define the reducers for the slice, which are functions that specify how the state should be updated in response to actions.
// 4. Export the action creators generated by createSlice() for each reducer.
// 5. Export the reducer function generated by createSlice() to be used in the store configuration.
